/**
 *              © 2025 Visa
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 **/
/** This file is autogenerated */
import { Routes } from '@angular/router';
import { TITLE_SEPARATOR, TITLE_SUFFIX } from 'apps/workshop/src/assets/app.constants';

export const verticalNavigationRoutes: Routes = [
	{ loadComponent: () => import('./vertical-navigation.docs').then(m => m.VerticalNavDocsComponent), path: '' },
	{ loadComponent: () => import('./active-element/active-element.docs').then(m => m.VerticalWithActiveElementNavComponent), path: 'active-element', title: 'Active element vertical navigation component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./alternate/alternate.docs').then(m => m.AlternateVerticalNavComponent), path: 'alternate', title: 'Alternate vertical navigation component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./alternate-with-active-element/alternate-with-active-element.docs').then(m => m.VerticalAlternateWithActiveElementNavComponent), path: 'alternate-with-active-element', title: 'Alternate with active element vertical navigation component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./alternate-with-icons/alternate-with-icons.docs').then(m => m.AlternateWithIconsVerticalNavComponent), path: 'alternate-with-icons', title: 'Alternate with icons vertical navigation component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./default/default.docs').then(m => m.DefaultVerticalNavComponent), path: 'default', title: 'Default vertical navigation component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./links-only/links-only.docs').then(m => m.LinksOnlyVerticalNavComponent), path: 'links-only', title: 'Links only vertical navigation component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./nested/nested.docs').then(m => m.NestedVerticalNavComponent), path: 'nested', title: 'Nested vertical navigation component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./nested-with-section-titles/nested-with-section-titles.docs').then(m => m.NestedWithSectionTitleVerticalNavComponent), path: 'nested-with-section-titles', title: 'Nested with section titles vertical navigation component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./with-icons/with-icons.docs').then(m => m.WithIconsVerticalNavComponent), path: 'with-icons', title: 'With icons vertical navigation component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./with-section-titles/with-section-titles.docs').then(m => m.WithSectionTitleVerticalNavComponent), path: 'with-section-titles', title: 'With section titles vertical navigation component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX }
];

export default verticalNavigationRoutes;