/**
 *              © 2025 Visa
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 **/
/** This file is autogenerated */
import { Routes } from '@angular/router';
import { TITLE_SEPARATOR, TITLE_SUFFIX } from 'apps/workshop/src/assets/app.constants';

export const accessibilityRoutes: Routes = [
	{ loadComponent: () => import('./accessibility.docs').then(m => m.AccessibilityComponent), path: '' },
	{ loadComponent: () => import('./progress-label/progress-label.docs').then(m => m.ScreenreaderOnlyProgressLabelComponent), path: 'progress-label', title: 'Progress label accessibility utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./table/table.docs').then(m => m.ScreenreaderOnlyTableComponent), path: 'table', title: 'Table accessibility utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./text/text.docs').then(m => m.ScreenreaderOnlyTextComponent), path: 'text', title: 'Text accessibility utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX }
];

export default accessibilityRoutes;