/**
 *              © 2025 Visa
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 **/
/** This file is autogenerated */
import { Routes } from '@angular/router';
import { TITLE_SEPARATOR, TITLE_SUFFIX } from 'apps/workshop/src/assets/app.constants';

export const anchorLinkMenuRoutes: Routes = [
	{ loadComponent: () => import('./anchor-link-menu.docs').then(m => m.AnchorLinkMenuDocsComponent), path: '' },
	{ loadComponent: () => import('./default/default.docs').then(m => m.NovaDefaultAnchorLinkMenuComponent), path: 'default', title: 'Default anchor link menu component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./default-nested/default-nested.docs').then(m => m.NovaDefaultNestedAnchorLinkMenuComponent), path: 'default-nested', title: 'Default nested anchor link menu component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./default-no-title/default-no-title.docs').then(m => m.NovaDefaultNoTitleAnchorLinkMenuComponent), path: 'default-no-title', title: 'Default no title anchor link menu component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./right-to-left/right-to-left.docs').then(m => m.NovaRightToLeftAnchorLinkMenuComponent), path: 'right-to-left', title: 'Right to left anchor link menu component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX }
];

export default anchorLinkMenuRoutes;