/**
 *              © 2025 Visa
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 **/
/** This file is autogenerated */
import { Routes } from '@angular/router';
import { TITLE_SEPARATOR, TITLE_SUFFIX } from 'apps/workshop/src/assets/app.constants';

export const dropdownMenuRoutes: Routes = [
	{ loadComponent: () => import('./dropdown-menu.docs').then(m => m.DropdownMenuDocsComponent), path: '' },
	{ loadComponent: () => import('./custom-buttons/custom-buttons.docs').then(m => m.CustomButtonsDropdownmenuComponent), path: 'custom-buttons', title: 'Custom buttons dropdown menu component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./custom-links/custom-links.docs').then(m => m.CustomLinksDropdownmenuComponent), path: 'custom-links', title: 'Custom links dropdown menu component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./form/form.docs').then(m => m.FormDropdownmenuComponent), path: 'form', title: 'Form dropdown menu component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./icon-button/icon-button.docs').then(m => m.IconButtonDropdownmenuComponent), path: 'icon-button', title: 'Icon button dropdown menu component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./multiselect-listbox/listbox.docs').then(m => m.MultiselectListboxDropdownmenuComponent), path: 'listbox', title: 'Listbox dropdown menu component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./native-popover/native-popover.docs').then(m => m.NativePopoverDropdownmenuComponent), path: 'native-popover', title: 'Native popover dropdown menu component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./tabs/tabs.docs').then(m => m.TabsDropdownmenuComponent), path: 'tabs', title: 'Tabs dropdown menu component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./text-button/text-button.docs').then(m => m.TextButtonDropdownmenuComponent), path: 'text-button', title: 'Text button dropdown menu component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX }
];

export default dropdownMenuRoutes;