/**
 *              Copyright (c) 2025 Visa, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 **/
/** This file is autogenerated */
import { Routes } from '@angular/router';
import { TITLE_SEPARATOR, TITLE_SUFFIX } from 'apps/workshop/src/assets/app.constants';

export const spacingRoutes: Routes = [
	{ loadComponent: () => import('./spacing.docs').then(m => m.SpacingComponent), path: '' },
	{ loadComponent: () => import('./column-gap/column-gap.docs').then(m => m.ColumnGapComponent), path: 'column-gap', title: 'Column gap spacing utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./gap/gap.docs').then(m => m.GapComponent), path: 'gap', title: 'Gap spacing utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./gap-inherit/gap-inherit.docs').then(m => m.GapInheritComponent), path: 'gap-inherit', title: 'Gap inherit spacing utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./gap-normal/gap-normal.docs').then(m => m.GapNormalComponent), path: 'gap-normal', title: 'Gap normal spacing utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./margin/margin.docs').then(m => m.MarginComponent), path: 'margin', title: 'Margin spacing utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./margin-bottom/margin-bottom.docs').then(m => m.MarginBottomComponent), path: 'margin-bottom', title: 'Margin bottom spacing utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./margin-horizontal/margin-horizontal.docs').then(m => m.MarginHorizontalComponent), path: 'margin-horizontal', title: 'Margin horizontal spacing utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./margin-inherit/margin-inherit.docs').then(m => m.MarginInheritComponent), path: 'margin-inherit', title: 'Margin inherit spacing utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./margin-left/margin-left.docs').then(m => m.MarginLeftComponent), path: 'margin-left', title: 'Margin left spacing utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./margin-right/margin-right.docs').then(m => m.MarginRightComponent), path: 'margin-right', title: 'Margin right spacing utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./margin-top/margin-top.docs').then(m => m.MarginTopComponent), path: 'margin-top', title: 'Margin top spacing utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./margin-vertical/margin-vertical.docs').then(m => m.MarginVerticalComponent), path: 'margin-vertical', title: 'Margin vertical spacing utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./padding/padding.docs').then(m => m.PaddingComponent), path: 'padding', title: 'Padding spacing utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./padding-bottom/padding-bottom.docs').then(m => m.PaddingBottomComponent), path: 'padding-bottom', title: 'Padding bottom spacing utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./padding-horizontal/padding-horizontal.docs').then(m => m.PaddingHorizontalComponent), path: 'padding-horizontal', title: 'Padding horizontal spacing utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./padding-inherit/padding-inherit.docs').then(m => m.PaddingInheritComponent), path: 'padding-inherit', title: 'Padding inherit spacing utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./padding-left/padding-left.docs').then(m => m.PaddingLeftComponent), path: 'padding-left', title: 'Padding left spacing utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./padding-right/padding-right.docs').then(m => m.PaddingRightComponent), path: 'padding-right', title: 'Padding right spacing utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./padding-top/padding-top.docs').then(m => m.PaddingTopComponent), path: 'padding-top', title: 'Padding top spacing utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./padding-vertical/padding-vertical.docs').then(m => m.PaddingVerticalComponent), path: 'padding-vertical', title: 'Padding vertical spacing utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./row-gap/row-gap.docs').then(m => m.RowGapComponent), path: 'row-gap', title: 'Row gap spacing utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX }
];

export default spacingRoutes;