/**
 *              Copyright (c) 2025 Visa, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 **/
/** This file is autogenerated */
import { Routes } from '@angular/router';
import { TITLE_SEPARATOR, TITLE_SUFFIX } from 'apps/workshop/src/assets/app.constants';

export const dateAndTimeSelectorsRoutes: Routes = [
	{ loadComponent: () => import('./date-and-time-selectors.docs').then(m => m.DateTimeSelectorsDocsComponent), path: '' },
	{ loadComponent: () => import('./date-range-default/date-range-default.docs').then(m => m.DefaultRangeDateTimeComponent), path: 'date-range-default', title: 'Date range default date and time selectors component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./date-range-stacked/date-range-stacked.docs').then(m => m.StackedRangeDateTimeComponent), path: 'date-range-stacked', title: 'Date range stacked date and time selectors component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./date-selector-values/date-selector-values.docs').then(m => m.DateSelectorValuesDateTimeComponent), path: 'date-selector-values', title: 'Date selector values date and time selectors component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./date-selector-with-disabled-dates/date-selector-with-disabled-dates.docs').then(m => m.WithDisabledDatesDateTimeComponent), path: 'date-selector-with-disabled-dates', title: 'Date selector with disabled dates date and time selectors component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./date-selector-with-error/date-selector-with-error.docs').then(m => m.InvalidDateSelectorDateTimeComponent), path: 'date-selector-with-error', title: 'Date selector with error date and time selectors component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./default-date-selector/default-date-selector.docs').then(m => m.DefaultDateSelectorDateTimeComponent), path: 'default-date-selector', title: 'Default date selector date and time selectors component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./default-time-selector/default-time-selector.docs').then(m => m.DefaultTimeSelectorDateTimeComponent), path: 'default-time-selector', title: 'Default time selector date and time selectors component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./disabled-date-selector/disabled-date-selector.docs').then(m => m.DisabledDateSelectorDateTimeComponent), path: 'disabled-date-selector', title: 'Disabled date selector date and time selectors component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./disabled-time-selector/disabled-time-selector.docs').then(m => m.DisabledTimeSelectorDateTimeComponent), path: 'disabled-time-selector', title: 'Disabled time selector date and time selectors component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./read-only-date-selector/read-only-date-selector.docs').then(m => m.ReadOnlyDateSelectorDateTimeComponent), path: 'read-only-date-selector', title: 'Read only date selector date and time selectors component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./read-only-time-selector/read-only-time-selector.docs').then(m => m.ReadOnlyTimeSelectorDateTimeComponent), path: 'read-only-time-selector', title: 'Read only time selector date and time selectors component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./time-selector-with-24-hour-clock/time-selector-with-24-hour-clock.docs').then(m => m.MilitaryTimeSelectorDateTimeComponent), path: 'time-selector-with-24-hour-clock', title: 'Time selector with 24 hour clock date and time selectors component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./time-selector-with-error/time-selector-with-error.docs').then(m => m.InvalidTimeSelectorDateTimeComponent), path: 'time-selector-with-error', title: 'Time selector with error date and time selectors component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX }
];

export default dateAndTimeSelectorsRoutes;