/**
 *              © 2025 Visa
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 **/
/** This file is autogenerated */
import { Routes } from '@angular/router';
import { TITLE_SEPARATOR, TITLE_SUFFIX } from 'apps/workshop/src/assets/app.constants';

export const switchRoutes: Routes = [
	{ loadComponent: () => import('./switch.docs').then(m => m.SwitchDocsComponent), path: '' },
	{ loadComponent: () => import('./disabled-off/disabled-off.docs').then(m => m.NovaDisabledOffSwitchDocsComponent), path: 'disabled-off', title: 'Disabled off switch component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./disabled-selected/disabled-selected.docs').then(m => m.NovaDisabledSelectedSwitchDocsComponent), path: 'disabled-selected', title: 'Disabled selected switch component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./optional-text/optional-text.docs').then(m => m.NovaOptionalTextSwitchDocsComponent), path: 'optional-text', title: 'Optional text switch component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./standard/standard.docs').then(m => m.NovaStandardSwitchComponent), path: 'standard', title: 'Standard switch component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX }
];

export default switchRoutes;