/**
 *              © 2025 Visa
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 **/
/** This file is autogenerated */
import { Routes } from '@angular/router';
import { TITLE_SEPARATOR, TITLE_SUFFIX } from 'apps/workshop/src/assets/app.constants';

export const radioRoutes: Routes = [
	{ loadComponent: () => import('./radio.docs').then(m => m.RadioDocsComponent), path: '' },
	{ loadComponent: () => import('./disabled/disabled.docs').then(m => m.DisabledRadioComponent), path: 'disabled', title: 'Disabled radio component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./disabled-and-selected/disabled-and-selected.docs').then(m => m.DisabledAndSelectedRadioComponent), path: 'disabled-and-selected', title: 'Disabled and selected radio component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./disabled-panel/disabled-panel.docs').then(m => m.DisabledPanelRadioComponent), path: 'disabled-panel', title: 'Disabled panel radio component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./error/error.docs').then(m => m.ErrorRadioComponent), path: 'error', title: 'Error radio component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./group/group.docs').then(m => m.GroupRadioComponent), path: 'group', title: 'Group radio component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./group-with-error/group-with-error.docs').then(m => m.GroupWithErrorRadioComponent), path: 'group-with-error', title: 'Group with error radio component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./group-with-selected/group-with-selected.docs').then(m => m.GroupWithSelectedRadioComponent), path: 'group-with-selected', title: 'Group with selected radio component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./horizontal-group/horizontal-group.docs').then(m => m.HorizontalGroupRadioComponent), path: 'horizontal-group', title: 'Horizontal group radio component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./model-driven-fb/model-driven-fb.docs').then(m => m.ModelDrivenFbRadioComponent), path: 'model-driven-fb', title: 'Model driven fb radio component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./model-driven-form/model-driven-form.docs').then(m => m.ModelDrivenFormRadioComponent), path: 'model-driven-form', title: 'Model driven form radio component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./panel/panel.docs').then(m => m.PanelRadioComponent), path: 'panel', title: 'Panel radio component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./panel-group/panel-group.docs').then(m => m.PanelGroupRadioComponent), path: 'panel-group', title: 'Panel group radio component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./panel-group-with-error/panel-group-with-error.docs').then(m => m.PanelGroupWithErrorRadioComponent), path: 'panel-group-with-error', title: 'Panel group with error radio component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./panel-without-description/panel-without-description.docs').then(m => m.PanelWithoutDescriptionRadioComponent), path: 'panel-without-description', title: 'Panel without description radio component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./selected/selected.docs').then(m => m.SelectedRadioComponent), path: 'selected', title: 'Selected radio component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./template-driven-form/template-driven-form.docs').then(m => m.TemplateDrivenFormRadioComponent), path: 'template-driven-form', title: 'Template driven form radio component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./with-description/with-description.docs').then(m => m.WithDescriptionRadioComponent), path: 'with-description', title: 'With description radio component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./with-label/with-label.docs').then(m => m.WithLabelRadioComponent), path: 'with-label', title: 'With label radio component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./without-visible-label/without-visible-label.docs').then(m => m.WithoutVisibleLabelRadioComponent), path: 'without-visible-label', title: 'Without visible label radio component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX }
];

export default radioRoutes;