/**
 *              Copyright (c) 2025 Visa, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 **/
/** This file is autogenerated */
import { Routes } from '@angular/router';
import { TITLE_SEPARATOR, TITLE_SUFFIX } from 'apps/workshop/src/assets/app.constants';

export const selectRoutes: Routes = [
	{ loadComponent: () => import('./select.docs').then(m => m.SelectDocsComponent), path: '' },
	{ loadComponent: () => import('./default/default.docs').then(m => m.DefaultSelectComponent), path: 'default', title: 'Default select component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./disabled/disabled.docs').then(m => m.DisabledSelectComponent), path: 'disabled', title: 'Disabled select component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./error/error.docs').then(m => m.ErrorSelectComponent), path: 'error', title: 'Error select component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./initial-value/initial-value.docs').then(m => m.InitialValueSelectComponent), path: 'initial-value', title: 'Initial value select component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./mock-data/mock-data.docs').then(m => m.MockDataSelectComponent), path: 'mock-data', title: 'Mock data select component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./model-driven/model-driven.docs').then(m => m.ModelDrivenSelectComponent), path: 'model-driven', title: 'Model driven select component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./model-driven-fb/model-driven-fb.docs').then(m => m.ModelDrivenFbSelectComponent), path: 'model-driven-fb', title: 'Model driven fb select component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./model-driven-form/model-driven-form.docs').then(m => m.ModelDrivenFormSelectComponent), path: 'model-driven-form', title: 'Model driven form select component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./model-driven-object/model-driven-object.docs').then(m => m.ModelDrivenObjectSelectComponent), path: 'model-driven-object', title: 'Model driven object select component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./read-only/read-only.docs').then(m => m.ReadOnlySelectComponent), path: 'read-only', title: 'Read only select component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./template-driven/template-driven.docs').then(m => m.TemplateDrivenSelectComponent), path: 'template-driven', title: 'Template driven select component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./template-driven-form/template-driven-form.docs').then(m => m.TemplateDrivenFormSelectComponent), path: 'template-driven-form', title: 'Template driven form select component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./template-driven-object/template-driven-object.docs').then(m => m.TemplateDrivenObjectSelectComponent), path: 'template-driven-object', title: 'Template driven object select component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./with-inline-label/with-inline-label.docs').then(m => m.WithInlineLabelSelectComponent), path: 'with-inline-label', title: 'With inline label select component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./with-inline-message/with-inline-message.docs').then(m => m.WithInlineMessageSelectComponent), path: 'with-inline-message', title: 'With inline message select component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX }
];

export default selectRoutes;