/**
 *              © 2025 Visa
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 **/
/** This file is autogenerated */
import { Routes } from '@angular/router';
import { TITLE_SEPARATOR, TITLE_SUFFIX } from 'apps/workshop/src/assets/app.constants';

export const listboxRoutes: Routes = [
	{ loadComponent: () => import('./listbox.docs').then(m => m.ListboxDocsComponent), path: '' },
	{ loadComponent: () => import('./data-test/data-test.docs').then(m => m.DataTestListboxComponent), path: 'data-test', title: 'Data test listbox component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./disabled-multi-select-listbox/disabled-multi-select-listbox.docs').then(m => m.DisabledMultiSelectListboxComponent), path: 'disabled-multi-select-listbox', title: 'Disabled multi select listbox listbox component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./disabled-single-select-listbox/disabled-single-select-listbox.docs').then(m => m.DisabledSingleSelectListboxComponent), path: 'disabled-single-select-listbox', title: 'Disabled single select listbox listbox component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./model-driven-fb/model-driven-fb.docs').then(m => m.ModelDrivenFBListboxComponent), path: 'model-driven-fb', title: 'Model driven fb listbox component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./model-driven-form/model-driven-form.docs').then(m => m.ModelDrivenFormListboxComponent), path: 'model-driven-form', title: 'Model driven form listbox component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./multi-select-checkbox-group/multi-select-checkbox-group.docs').then(m => m.MultiSelectCheckboxGroupListboxComponent), path: 'multi-select-checkbox-group', title: 'Multi select checkbox group listbox component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./multi-select-checkbox-group-with-arrow-nav/multi-select-checkbox-group-with-arrow-nav.docs').then(m => m.MultiSelectCheckboxGroupWithArrowsListboxComponent), path: 'multi-select-checkbox-group-with-arrow-nav', title: 'Multi select checkbox group with arrow nav listbox component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./multi-select-default/multi-select-default.docs').then(m => m.MultiSelectDefaultListboxComponent), path: 'multi-select-default', title: 'Multi select default listbox component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./multi-select-model-driven/multi-select-model-driven.docs').then(m => m.MultiSelectModelDrivenListboxComponent), path: 'multi-select-model-driven', title: 'Multi select model driven listbox component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./multi-select-scroll-to-index/multi-select-scroll-to-index.docs').then(m => m.MultiSelectScrollToIndexListboxComponent), path: 'multi-select-scroll-to-index', title: 'Multi select scroll to index listbox component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./multi-select-template-driven/multi-select-template-driven.docs').then(m => m.MultiSelectTemplateDrivenListboxComponent), path: 'multi-select-template-driven', title: 'Multi select template driven listbox component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./multi-select-with-disabled-item/multi-select-with-disabled-item.docs').then(m => m.MultiSelectWithDisabledItemListboxComponent), path: 'multi-select-with-disabled-item', title: 'Multi select with disabled item listbox component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./multi-select-with-error/multi-select-with-error.docs').then(m => m.MultiSelectWithErrorListboxComponent), path: 'multi-select-with-error', title: 'Multi select with error listbox component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./multi-select-with-inline-message/multi-select-with-inline-message.docs').then(m => m.MultiSelectWithInlineMessageListboxComponent), path: 'multi-select-with-inline-message', title: 'Multi select with inline message listbox component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./multi-select-with-resize/multi-select-with-resize.docs').then(m => m.MultiSelectWithResizeListboxComponent), path: 'multi-select-with-resize', title: 'Multi select with resize listbox component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./multi-select-with-selected-item/multi-select-with-selected-item.docs').then(m => m.MultiSelectWithSelectedItemListboxComponent), path: 'multi-select-with-selected-item', title: 'Multi select with selected item listbox component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./single-select-automatic-selection/single-select-automatic-selection.docs').then(m => m.AutomaticSingleSelectListboxComponent), path: 'single-select-automatic-selection', title: 'Single select automatic selection listbox component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./single-select-default/single-select-default.docs').then(m => m.SingleSelectDefaultListboxComponent), path: 'single-select-default', title: 'Single select default listbox component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./single-select-model-driven/single-select-model-driven.docs').then(m => m.SingleSelectModelDrivenListboxComponent), path: 'single-select-model-driven', title: 'Single select model driven listbox component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./single-select-radio-group/single-select-radio-group.docs').then(m => m.SingleSelectRadioGroupListboxComponent), path: 'single-select-radio-group', title: 'Single select radio group listbox component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./single-select-scroll-to-index/single-select-scroll-to-index.docs').then(m => m.SingleSelectScrollToIndexListboxComponent), path: 'single-select-scroll-to-index', title: 'Single select scroll to index listbox component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./single-select-template-driven/single-select-template-driven.docs').then(m => m.SingleSelectTemplateDrivenListboxComponent), path: 'single-select-template-driven', title: 'Single select template driven listbox component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./single-select-with-disabled-item/single-select-with-disabled-item.docs').then(m => m.SingleSelectWithDisabledItemListboxComponent), path: 'single-select-with-disabled-item', title: 'Single select with disabled item listbox component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./single-select-with-error/single-select-with-error.docs').then(m => m.SingleSelectWithErrorListboxComponent), path: 'single-select-with-error', title: 'Single select with error listbox component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./single-select-with-inline-message/single-select-with-inline-message.docs').then(m => m.SingleSelectWithInlineMessageListboxComponent), path: 'single-select-with-inline-message', title: 'Single select with inline message listbox component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./single-select-with-resize/single-select-with-resize.docs').then(m => m.SingleSelectWithResizeListboxComponent), path: 'single-select-with-resize', title: 'Single select with resize listbox component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./single-select-with-selected-item/single-select-with-selected-item.docs').then(m => m.SingleSelectWithSelectedItemListboxComponent), path: 'single-select-with-selected-item', title: 'Single select with selected item listbox component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./template-driven-form/template-driven-form.docs').then(m => m.TemplateDrivenFormListboxComponent), path: 'template-driven-form', title: 'Template driven form listbox component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX }
];

export default listboxRoutes;