/**
 *              © 2025 Visa
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 **/
/** This file is autogenerated */
import { Routes } from '@angular/router';
import { TITLE_SEPARATOR, TITLE_SUFFIX } from 'apps/workshop/src/assets/app.constants';

export const tabsRoutes: Routes = [
	{ loadComponent: () => import('./tabs.docs').then(m => m.TabsDocsComponent), path: '' },
	{ loadComponent: () => import('./automatic-activation/automatic-activation.docs').then(m => m.AutomaticActivationTabsComponent), path: 'automatic-activation', title: 'Automatic activation tabs component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./horizontal-alternate/horizontal-alternate.docs').then(m => m.HorizontalAlternateTabsComponent), path: 'horizontal-alternate', title: 'Horizontal alternate tabs component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./horizontal-default/horizontal-default.docs').then(m => m.HorizontalDefaultTabsComponent), path: 'horizontal-default', title: 'Horizontal default tabs component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./horizontal-disabled/horizontal-disabled.docs').then(m => m.HorizontalDisabledTabsComponent), path: 'horizontal-disabled', title: 'Horizontal disabled tabs component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./horizontal-with-icon/horizontal-with-icon.docs').then(m => m.HorizontalWithIconTabsComponent), path: 'horizontal-with-icon', title: 'Horizontal with icon tabs component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./horizontal-with-menu/horizontal-with-menu.docs').then(m => m.HorizontalWithMenuTabsComponent), path: 'horizontal-with-menu', title: 'Horizontal with menu tabs component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./stacked-alternate/stacked-alternate.docs').then(m => m.StackedAlternateTabsComponent), path: 'stacked-alternate', title: 'Stacked alternate tabs component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./stacked-default/stacked-default.docs').then(m => m.StackedDefaultTabsComponent), path: 'stacked-default', title: 'Stacked default tabs component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./stacked-disabled/stacked-disabled.docs').then(m => m.StackedDisabledTabsComponent), path: 'stacked-disabled', title: 'Stacked disabled tabs component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./stacked-with-notifications/stacked-with-notifications.docs').then(m => m.StackedWithNotificationsTabsComponent), path: 'stacked-with-notifications', title: 'Stacked with notifications tabs component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./tab-panel/tab-panel.docs').then(m => m.TabPanelTabsComponent), path: 'tab-panel', title: 'Tab panel tabs component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./vertical-alternate/vertical-alternate.docs').then(m => m.VerticalAlternateTabsComponent), path: 'vertical-alternate', title: 'Vertical alternate tabs component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./vertical-default/vertical-default.docs').then(m => m.VerticalDefaultTabsComponent), path: 'vertical-default', title: 'Vertical default tabs component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./vertical-disabled/vertical-disabled.docs').then(m => m.VerticalDisabledTabsComponent), path: 'vertical-disabled', title: 'Vertical disabled tabs component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./vertical-with-icon/vertical-with-icon.docs').then(m => m.VerticalWithIconTabsComponent), path: 'vertical-with-icon', title: 'Vertical with icon tabs component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./vertical-with-menu/vertical-with-menu.docs').then(m => m.VerticalWithMenuTabsComponent), path: 'vertical-with-menu', title: 'Vertical with menu tabs component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./without-arrow-navigation/without-arrow-navigation.docs').then(m => m.WithoutArrowNavigationTabsComponent), path: 'without-arrow-navigation', title: 'Without arrow navigation tabs component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX }
];

export default tabsRoutes;