/**
 *              Copyright (c) 2025 Visa, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 **/
/** This file is autogenerated */
import { Routes } from '@angular/router';
import { TITLE_SEPARATOR, TITLE_SUFFIX } from 'apps/workshop/src/assets/app.constants';

export const flagRoutes: Routes = [
	{ loadComponent: () => import('./flag.docs').then(m => m.FlagDocsComponent), path: '' },
	{ loadComponent: () => import('./default-info-flag/default-info-flag.docs').then(m => m.DefaultInfoFlagComponent), path: 'default-info-flag', title: 'Default info flag flag component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./default-info-flag-title/default-info-flag-title.docs').then(m => m.DefaultInfoFlagWithTitleComponent), path: 'default-info-flag-title', title: 'Default info flag title flag component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./empty-error/empty-error.docs').then(m => m.EmptyErrorFlagComponent), path: 'empty-error', title: 'Empty error flag component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./empty-info/empty-info.docs').then(m => m.EmptyFlagComponent), path: 'empty-info', title: 'Empty info flag component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./empty-success/empty-success.docs').then(m => m.EmptySuccessFlagComponent), path: 'empty-success', title: 'Empty success flag component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./empty-warning/empty-warning.docs').then(m => m.EmptyWarningFlagComponent), path: 'empty-warning', title: 'Empty warning flag component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./error-flag/error-flag.docs').then(m => m.ErrorFlagComponent), path: 'error-flag', title: 'Error flag flag component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./error-flag-title/error-flag-title.docs').then(m => m.ErrorFlagWithTitleComponent), path: 'error-flag-title', title: 'Error flag title flag component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./error-flag-with-action-button/error-flag-with-action-button.docs').then(m => m.ErrorFlagWithActionButtonFlagComponent), path: 'error-flag-with-action-button', title: 'Error flag with action button flag component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./error-flag-with-link/error-flag-with-link.docs').then(m => m.ErrorFlagWithLinkFlagComponent), path: 'error-flag-with-link', title: 'Error flag with link flag component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./error-without-close-icon-button/error-without-close-icon-button.docs').then(m => m.ErrorWithoutCloseIconButtonFlagComponent), path: 'error-without-close-icon-button', title: 'Error without close icon button flag component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./info-flag-with-action-button/info-flag-with-action-button.docs').then(m => m.InfoFlagWithActionButtonFlagComponent), path: 'info-flag-with-action-button', title: 'Info flag with action button flag component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./info-flag-with-link/info-flag-with-link.docs').then(m => m.InfoFlagWithLinkFlagComponent), path: 'info-flag-with-link', title: 'Info flag with link flag component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./info-without-close-icon-button/info-without-close-icon-button.docs').then(m => m.InfoWithoutCloseIconButtonFlagComponent), path: 'info-without-close-icon-button', title: 'Info without close icon button flag component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./success-flag/success-flag.docs').then(m => m.SuccessFlagComponent), path: 'success-flag', title: 'Success flag flag component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./success-flag-title/success-flag-title.docs').then(m => m.SuccessFlagWithTitleComponent), path: 'success-flag-title', title: 'Success flag title flag component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./success-flag-with-action-button/success-flag-with-action-button.docs').then(m => m.SuccessFlagWithActionButtonFlagComponent), path: 'success-flag-with-action-button', title: 'Success flag with action button flag component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./success-flag-with-link/success-flag-with-link.docs').then(m => m.SuccessFlagWithLinkFlagComponent), path: 'success-flag-with-link', title: 'Success flag with link flag component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./success-without-close-icon-button/success-without-close-icon-button.docs').then(m => m.SuccessWithoutCloseIconButtonFlagComponent), path: 'success-without-close-icon-button', title: 'Success without close icon button flag component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./warning-flag/warning-flag.docs').then(m => m.WarningFlagComponent), path: 'warning-flag', title: 'Warning flag flag component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./warning-flag-title/warning-flag-title.docs').then(m => m.WarningFlagWithTitleComponent), path: 'warning-flag-title', title: 'Warning flag title flag component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./warning-flag-with-action-button/warning-flag-with-action-button.docs').then(m => m.WarningFlagWithActionButtonFlagComponent), path: 'warning-flag-with-action-button', title: 'Warning flag with action button flag component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./warning-flag-with-link/warning-flag-with-link.docs').then(m => m.WarningFlagWithLinkFlagComponent), path: 'warning-flag-with-link', title: 'Warning flag with link flag component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./warning-without-close-icon-button/warning-without-close-icon-button.docs').then(m => m.WarningWithoutCloseIconButtonFlagComponent), path: 'warning-without-close-icon-button', title: 'Warning without close icon button flag component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX }
];

export default flagRoutes;