/**
 *              Copyright (c) 2025 Visa, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 **/
/** This file is autogenerated */
import { Routes } from '@angular/router';
import { TITLE_SEPARATOR, TITLE_SUFFIX } from 'apps/workshop/src/assets/app.constants';

export const toggleRoutes: Routes = [
	{ loadComponent: () => import('./toggle.docs').then(m => m.ToggleDocsComponent), path: '' },
	{ loadComponent: () => import('./default/default.docs').then(m => m.NovaToggleDefaultComponent), path: 'default', title: 'Default toggle component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./disabled/disabled.docs').then(m => m.NovaToggleDisabledComponent), path: 'disabled', title: 'Disabled toggle component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./icon-only/icon-only.docs').then(m => m.NovaToggleIconOnlyComponent), path: 'icon-only', title: 'Icon only toggle component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./model-driven-fb/model-driven-fb.docs').then(m => m.ModelDrivenFbToggleComponent), path: 'model-driven-fb', title: 'Model driven fb toggle component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./model-driven-form/model-driven-form.docs').then(m => m.ModelDrivenFormToggleComponent), path: 'model-driven-form', title: 'Model driven form toggle component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./multi-select/multi-select.docs').then(m => m.NovaMultiSelectToggleComponent), path: 'multi-select', title: 'Multi select toggle component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./multi-select-with-checkboxes/multi-select-with-checkboxes.docs').then(m => m.MultiSelectCheckboxesToggleComponent), path: 'multi-select-with-checkboxes', title: 'Multi select with checkboxes toggle component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./one-button-disabled/one-button-disabled.docs').then(m => m.NovaToggleOneButtonDisabledComponent), path: 'one-button-disabled', title: 'One button disabled toggle component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./single-select-with-radio-buttons/single-select-with-radio-buttons.docs').then(m => m.SingleSelectRadioButtonToggleComponent), path: 'single-select-with-radio-buttons', title: 'Single select with radio buttons toggle component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./standalone-multi-select/standalone-multi-select.docs').then(m => m.NovaStandaloneMultiSelectToggleComponent), path: 'standalone-multi-select', title: 'Standalone multi select toggle component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./template-driven-form/template-driven-form.docs').then(m => m.TemplateDrivenFormToggleComponent), path: 'template-driven-form', title: 'Template driven form toggle component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./with-leading-icon/with-leading-icon.docs').then(m => m.NovaToggleWithLeadingIconComponent), path: 'with-leading-icon', title: 'With leading icon toggle component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./with-trailing-icon/with-trailing-icon.docs').then(m => m.NovaToggleWithTrailingIconComponent), path: 'with-trailing-icon', title: 'With trailing icon toggle component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX }
];

export default toggleRoutes;