/**
 *              © 2025 Visa
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 **/
/** This file is autogenerated */
import { Routes } from '@angular/router';
import { TITLE_SEPARATOR, TITLE_SUFFIX } from 'apps/workshop/src/assets/app.constants';

export const paginationRoutes: Routes = [
	{ loadComponent: () => import('./pagination.docs').then(m => m.PaginationDocsComponent), path: '' },
	{ loadComponent: () => import('./_default-last-page/default-last-page.docs').then(m => m.PaginationControlDefaultLastPageComponent), path: 'default-last-page', title: 'Default last page pagination component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./_default-middle-page/default-middle-page.docs').then(m => m.PaginationControlDefaultMiddlePageComponent), path: 'default-middle-page', title: 'Default middle page pagination component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./_multiple-paginations/multiple-paginations.docs').then(m => m._MultiplePaginationsComponent), path: 'multiple-paginations', title: 'Multiple paginations pagination component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./_selected-in-middle/selected-in-middle.docs').then(m => m.PaginationControlSelectedInMiddleComponent), path: 'selected-in-middle', title: 'Selected in middle pagination component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./_slim/slim.docs').then(m => m.PaginationControlSlimComponent), path: 'slim', title: 'Slim pagination component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./_slim-with-count/slim-with-count.docs').then(m => m.PaginationControlSlimWithCountComponent), path: 'slim-with-count', title: 'Slim with count pagination component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./_table/table.docs').then(m => m.PaginationControlTableComponent), path: 'table', title: 'Table pagination component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./default-first-page/default-first-page.docs').then(m => m.PaginationDefaultFirstPageComponent), path: 'default-first-page', title: 'Default first page pagination component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./default-last-page/default-last-page.docs').then(m => m.PaginationDefaultLastPageComponent), path: 'default-last-page', title: 'Default last page pagination component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./default-middle-page/default-middle-page.docs').then(m => m.PaginationDefaultMiddlePageComponent), path: 'default-middle-page', title: 'Default middle page pagination component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./multiple-paginations/multiple-paginations.docs').then(m => m.MultiplePaginationsComponent), path: 'multiple-paginations', title: 'Multiple paginations pagination component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./selected-in-middle/selected-in-middle.docs').then(m => m.PaginationSelectedInMiddleComponent), path: 'selected-in-middle', title: 'Selected in middle pagination component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./slim/slim.docs').then(m => m.PaginationSlimComponent), path: 'slim', title: 'Slim pagination component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./slim-with-count/slim-with-count.docs').then(m => m.PaginationSlimWithCountComponent), path: 'slim-with-count', title: 'Slim with count pagination component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./table/table.docs').then(m => m.PaginationTableComponent), path: 'table', title: 'Table pagination component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX }
];

export default paginationRoutes;