/**
 *              Copyright (c) 2025 Visa, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 **/
/** This file is autogenerated */
import { Routes } from '@angular/router';
import { TITLE_SEPARATOR, TITLE_SUFFIX } from 'apps/workshop/src/assets/app.constants';

export const typographyRoutes: Routes = [
	{ loadComponent: () => import('./typography.docs').then(m => m.TypographyComponent), path: '' },
	{ loadComponent: () => import('./body-1/body-1.docs').then(m => m.Body1Component), path: 'body-1', title: 'Body 1 typography utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./body-2/body-2.docs').then(m => m.Body2Component), path: 'body-2', title: 'Body 2 typography utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./body-2-bold/body-2-bold.docs').then(m => m.Body2BoldComponent), path: 'body-2-bold', title: 'Body 2 bold typography utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./body-2-medium/body-2-medium.docs').then(m => m.Body2MediumComponent), path: 'body-2-medium', title: 'Body 2 medium typography utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./body-3/body-3.docs').then(m => m.Body3Component), path: 'body-3', title: 'Body 3 typography utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./button-large/button-large.docs').then(m => m.ButtonLargeComponent), path: 'button-large', title: 'Button large typography utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./button-medium/button-medium.docs').then(m => m.ButtonMediumComponent), path: 'button-medium', title: 'Button medium typography utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./button-small/button-small.docs').then(m => m.ButtonSmallComponent), path: 'button-small', title: 'Button small typography utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./color-active/color-active.docs').then(m => m.ColorActiveComponent), path: 'color-active', title: 'Color active typography utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./color-default/color-default.docs').then(m => m.ColorDefaultComponent), path: 'color-default', title: 'Color default typography utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./color-on-active/color-on-active.docs').then(m => m.ColorOnActiveComponent), path: 'color-on-active', title: 'Color on active typography utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./color-subtle/color-subtle.docs').then(m => m.ColorSubtleComponent), path: 'color-subtle', title: 'Color subtle typography utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./display-1/display-1.docs').then(m => m.Display1Component), path: 'display-1', title: 'Display 1 typography utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./display-2/display-2.docs').then(m => m.Display2Component), path: 'display-2', title: 'Display 2 typography utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./headline-1/headline-1.docs').then(m => m.Headline1Component), path: 'headline-1', title: 'Headline 1 typography utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./headline-2/headline-2.docs').then(m => m.Headline2Component), path: 'headline-2', title: 'Headline 2 typography utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./headline-3/headline-3.docs').then(m => m.Headline3Component), path: 'headline-3', title: 'Headline 3 typography utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./headline-4/headline-4.docs').then(m => m.Headline4Component), path: 'headline-4', title: 'Headline 4 typography utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./label/label.docs').then(m => m.LabelComponent), path: 'label', title: 'Label typography utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./label-active/label-active.docs').then(m => m.LabelActiveComponent), path: 'label-active', title: 'Label active typography utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./label-large/label-large.docs').then(m => m.LabelLargeComponent), path: 'label-large', title: 'Label large typography utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./label-large-active/label-large-active.docs').then(m => m.LabelLargeActiveComponent), path: 'label-large-active', title: 'Label large active typography utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./label-small/label-small.docs').then(m => m.LabelSmallComponent), path: 'label-small', title: 'Label small typography utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./label-small-active/label-small-active.docs').then(m => m.LabelSmallActiveComponent), path: 'label-small-active', title: 'Label small active typography utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./overline/overline.docs').then(m => m.OverlineComponent), path: 'overline', title: 'Overline typography utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./subtitle-1/subtitle-1.docs').then(m => m.Subtitle1Component), path: 'subtitle-1', title: 'Subtitle 1 typography utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./subtitle-2/subtitle-2.docs').then(m => m.Subtitle2Component), path: 'subtitle-2', title: 'Subtitle 2 typography utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./subtitle-3/subtitle-3.docs').then(m => m.Subtitle3Component), path: 'subtitle-3', title: 'Subtitle 3 typography utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX }
];

export default typographyRoutes;