/**
 *              © 2025 Visa
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 **/
/** This file is autogenerated */
import { Routes } from '@angular/router';
import { TITLE_SEPARATOR, TITLE_SUFFIX } from 'apps/workshop/src/assets/app.constants';

export const linkRoutes: Routes = [
	{ loadComponent: () => import('./link.docs').then(m => m.LinkDocsComponent), path: '' },
	{ loadComponent: () => import('./alternate/alternate.docs').then(m => m.AlternateLinkComponent), path: 'alternate', title: 'Alternate link component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./button-as-disabled-link/button-as-disabled-link.docs').then(m => m.ButtonAsDisabledLinkLinkComponent), path: 'button-as-disabled-link', title: 'Button as disabled link link component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./button-as-link/button-as-link.docs').then(m => m.ButtonAsLinkLinkComponent), path: 'button-as-link', title: 'Button as link link component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./default/default.docs').then(m => m.DefaultLinkComponent), path: 'default', title: 'Default link component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./disabled/disabled.docs').then(m => m.DisabledLinkComponent), path: 'disabled', title: 'Disabled link component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./inline/inline.docs').then(m => m.InlineLinkComponent), path: 'inline', title: 'Inline link component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./link-with-leading-icon/link-with-leading-icon.docs').then(m => m.LinkWithLeadingIconComponent), path: 'link-with-leading-icon', title: 'Link with leading icon link component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./link-with-trailing-icon/link-with-trailing-icon.docs').then(m => m.LinkWithTrailingIconComponent), path: 'link-with-trailing-icon', title: 'Link with trailing icon link component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./open-in-new-tab/open-in-new-tab.docs').then(m => m.LinkOpenInNewTab), path: 'open-in-new-tab', title: 'Open in new tab link component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./without-underline/without-underline.docs').then(m => m.WithoutUnderlineLinkComponent), path: 'without-underline', title: 'Without underline link component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX }
];

export default linkRoutes;