/**
 *              Copyright (c) 2025 Visa, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 **/
/** This file is autogenerated */
import { Routes } from '@angular/router';
import { TITLE_SEPARATOR, TITLE_SUFFIX } from 'apps/workshop/src/assets/app.constants';

export const contentCardRoutes: Routes = [
	{ loadComponent: () => import('./content-card.docs').then(m => m.ContentCardDocsComponent), path: '' },
	{ loadComponent: () => import('./category/category.docs').then(m => m.NovaCategoryCardComponent), path: 'category', title: 'Category content card component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./clickable-card/clickable-card.docs').then(m => m.NovaClickableCardComponent), path: 'clickable-card', title: 'Clickable card content card component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./clickable-card-disabled/clickable-card-disabled.docs').then(m => m.NovaClickableCardDisabledComponent), path: 'clickable-card-disabled', title: 'Clickable card disabled content card component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./compact/compact.docs').then(m => m.NovaCompactCardComponent), path: 'compact', title: 'Compact content card component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./compact-dashboard/compact-dashboard.docs').then(m => m.NovaCompactDashboardCardComponent), path: 'compact-dashboard', title: 'Compact dashboard content card component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./default/default.docs').then(m => m.NovaDefaultCardComponent), path: 'default', title: 'Default content card component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./default-dashboard/default-dashboard.docs').then(m => m.NovaDefaultDashboardCardComponent), path: 'default-dashboard', title: 'Default dashboard content card component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./default-with-ui-buttons/default-with-ui-buttons.docs').then(m => m.NovaDefaultWithUIButtonsCardComponent), path: 'default-with-ui-buttons', title: 'Default with ui buttons content card component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./icon/icon.docs').then(m => m.NovaIconCardComponent), path: 'icon', title: 'Icon content card component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./image/image.docs').then(m => m.NovaImageCardComponent), path: 'image', title: 'Image content card component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX }
];

export default contentCardRoutes;