/**
 *              Copyright (c) 2025 Visa, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 **/
/** This file is autogenerated */
import { Routes } from '@angular/router';
import { TITLE_SEPARATOR, TITLE_SUFFIX } from 'apps/workshop/src/assets/app.constants';

export const tooltipRoutes: Routes = [
	{ loadComponent: () => import('./tooltip.docs').then(m => m.TooltipDocsComponent), path: '' },
	{ loadComponent: () => import('./bottom/bottom.docs').then(m => m.BottomTooltipComponent), path: 'bottom', title: 'Bottom tooltip component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./custom-events/custom-events.docs').then(m => m.CustomEventsTooltipComponent), path: 'custom-events', title: 'Custom events tooltip component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./custom-middleware/custom-middleware.docs').then(m => m.CustomMiddlewareTooltipComponent), path: 'custom-middleware', title: 'Custom middleware tooltip component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./left/left.docs').then(m => m.LeftTooltipComponent), path: 'left', title: 'Left tooltip component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./right/right.docs').then(m => m.RightTooltipComponent), path: 'right', title: 'Right tooltip component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./top/top.docs').then(m => m.TopTooltipComponent), path: 'top', title: 'Top tooltip component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./with-arrow/with-arrow.docs').then(m => m.WithArrowTooltipComponent), path: 'with-arrow', title: 'With arrow tooltip component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX }
];

export default tooltipRoutes;