/**
 *              Copyright (c) 2025 Visa, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 **/
/** This file is autogenerated */
import { Routes } from '@angular/router';
import { TITLE_SEPARATOR, TITLE_SUFFIX } from 'apps/workshop/src/assets/app.constants';

export const bannerRoutes: Routes = [
	{ loadComponent: () => import('./banner.docs').then(m => m.BannerDocsComponent), path: '' },
	{ loadComponent: () => import('./empty-error/empty-error.docs').then(m => m.EmptyErrorBannerComponent), path: 'empty-error', title: 'Empty error banner component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./empty-info/empty-info.docs').then(m => m.EmptyInfoBannerComponent), path: 'empty-info', title: 'Empty info banner component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./empty-success/empty-success.docs').then(m => m.EmptySuccessBannerComponent), path: 'empty-success', title: 'Empty success banner component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./empty-warning/empty-warning.docs').then(m => m.EmptyWarningBannerComponent), path: 'empty-warning', title: 'Empty warning banner component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./global-banner/global-banner.docs').then(m => m.GlobalBannerExampleComponent), path: 'global-banner', title: 'Global banner banner component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./nova-default-info-banner/nova-default-info-banner.docs').then(m => m.DefaultInfoBannerBannerComponent), path: 'nova-default-info-banner', title: 'Nova default info banner banner component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./nova-default-info-banner-persistent/nova-default-info-banner-persistent.docs').then(m => m.DefaultInfoBannerWithPersistentComponent), path: 'nova-default-info-banner-persistent', title: 'Nova default info banner persistent banner component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./nova-default-info-banner-title/nova-default-info-banner-title.docs').then(m => m.DefaultInfoBannerWithTitleComponent), path: 'nova-default-info-banner-title', title: 'Nova default info banner title banner component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./nova-error-banner/nova-error-banner.docs').then(m => m.ErrorBannerBannerComponent), path: 'nova-error-banner', title: 'Nova error banner banner component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./nova-error-banner-persistent/nova-error-banner-persistent.docs').then(m => m.ErrorPersistentBannerComponent), path: 'nova-error-banner-persistent', title: 'Nova error banner persistent banner component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./nova-error-banner-title/nova-error-banner-title.docs').then(m => m.ErrorTitleBannerComponent), path: 'nova-error-banner-title', title: 'Nova error banner title banner component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./nova-error-banner-with-action-button/nova-error-banner-with-action-button.docs').then(m => m.ErrorBannerWithActionButtonBannerComponent), path: 'nova-error-banner-with-action-button', title: 'Nova error banner with action button banner component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./nova-error-banner-with-link/nova-error-banner-with-link.docs').then(m => m.ErrorBannerWithLinkBannerComponent), path: 'nova-error-banner-with-link', title: 'Nova error banner with link banner component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./nova-info-banner-with-action-button/nova-info-banner-with-action-button.docs').then(m => m.InfoBannerWithActionButtonBannerComponent), path: 'nova-info-banner-with-action-button', title: 'Nova info banner with action button banner component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./nova-info-banner-with-link/nova-info-banner-with-link.docs').then(m => m.InfoBannerWithLinkBannerComponent), path: 'nova-info-banner-with-link', title: 'Nova info banner with link banner component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./nova-success-banner/nova-success-banner.docs').then(m => m.SuccessBannerBannerComponent), path: 'nova-success-banner', title: 'Nova success banner banner component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./nova-success-banner-persistent/nova-success-banner-persistent.docs').then(m => m.SuccessPersistentBannerComponent), path: 'nova-success-banner-persistent', title: 'Nova success banner persistent banner component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./nova-success-banner-title/nova-success-banner-title.docs').then(m => m.SuccessTitleBannerComponent), path: 'nova-success-banner-title', title: 'Nova success banner title banner component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./nova-success-banner-with-action-button/nova-success-banner-with-action-button.docs').then(m => m.SuccessBannerWithActionButtonBannerComponent), path: 'nova-success-banner-with-action-button', title: 'Nova success banner with action button banner component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./nova-success-banner-with-link/nova-success-banner-with-link.docs').then(m => m.SuccessBannerWithLinkBannerComponent), path: 'nova-success-banner-with-link', title: 'Nova success banner with link banner component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./nova-warning-banner/nova-warning-banner.docs').then(m => m.WarningBannerBannerComponent), path: 'nova-warning-banner', title: 'Nova warning banner banner component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./nova-warning-banner-persistent/nova-warning-banner-persistent.docs').then(m => m.WarningPersistentBannerComponent), path: 'nova-warning-banner-persistent', title: 'Nova warning banner persistent banner component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./nova-warning-banner-title/nova-warning-banner-title.docs').then(m => m.WarningTitleBannerComponent), path: 'nova-warning-banner-title', title: 'Nova warning banner title banner component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./nova-warning-banner-with-action-button/nova-warning-banner-with-action-button.docs').then(m => m.WarningBannerWithActionButtonBannerComponent), path: 'nova-warning-banner-with-action-button', title: 'Nova warning banner with action button banner component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./nova-warning-banner-with-link/nova-warning-banner-with-link.docs').then(m => m.WarningBannerWithLinkBannerComponent), path: 'nova-warning-banner-with-link', title: 'Nova warning banner with link banner component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX }
];

export default bannerRoutes;