/**
 *              © 2025 Visa
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 **/
/** This file is autogenerated */
import { Routes } from '@angular/router';
import { TITLE_SEPARATOR, TITLE_SUFFIX } from 'apps/workshop/src/assets/app.constants';

export const colorSelectorRoutes: Routes = [
	{ loadComponent: () => import('./color-selector.docs').then(m => m.ColorSelectorDocsComponent), path: '' },
	{ loadComponent: () => import('./available-values/available-values.docs').then(m => m.AvailableValuesColorSelectorComponent), path: 'available-values', title: 'Available values color selector component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./default/default.docs').then(m => m.DefaultColorSelectorComponent), path: 'default', title: 'Default color selector component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./disabled/disabled.docs').then(m => m.DisabledColorSelectorComponent), path: 'disabled', title: 'Disabled color selector component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX }
];

export default colorSelectorRoutes;