/**
 *              © 2025 Visa
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 **/
/** This file is autogenerated */
import { Routes } from '@angular/router';
import { TITLE_SEPARATOR, TITLE_SUFFIX } from 'apps/workshop/src/assets/app.constants';

export const badgeRoutes: Routes = [
	{ loadComponent: () => import('./badge.docs').then(m => m.BadgeDocsComponent), path: '' },
	{ loadComponent: () => import('./default/default.docs').then(m => m.DefaultBadgeComponent), path: 'default', title: 'Default badge component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./long-number/long-number.docs').then(m => m.LongNumberBadgeComponent), path: 'long-number', title: 'Long number badge component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./negative-icon-no-background/negative-icon-no-background.docs').then(m => m.NegativeIconNoBackgroundBadgeComponent), path: 'negative-icon-no-background', title: 'Negative icon no background badge component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./negative-icon-only/negative-icon-only.docs').then(m => m.NegativeIconOnlyBadgeComponent), path: 'negative-icon-only', title: 'Negative icon only badge component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./negative-label-only/negative-label-only.docs').then(m => m.NegativeLabelOnlyBadgeComponent), path: 'negative-label-only', title: 'Negative label only badge component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./negative-no-background/negative-no-background.docs').then(m => m.NegativeNoBackgroundBadgeComponent), path: 'negative-no-background', title: 'Negative no background badge component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./negative-number/negative-number.docs').then(m => m.NegativeNumberBadgeComponent), path: 'negative-number', title: 'Negative number badge component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./negative-number-no-background/negative-number-no-background.docs').then(m => m.NegativeNumberNoBackgroundBadgeComponent), path: 'negative-number-no-background', title: 'Negative number no background badge component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./negative-with-ellipse/negative-with-ellipse.docs').then(m => m.NegativeWithEllipseBadgeComponent), path: 'negative-with-ellipse', title: 'Negative with ellipse badge component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./negative-with-icon/negative-with-icon.docs').then(m => m.NegativeWithIconBadgeComponent), path: 'negative-with-icon', title: 'Negative with icon badge component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./neutral-icon-no-background/neutral-icon-no-background.docs').then(m => m.NeutralIconNoBackgroundBadgeComponent), path: 'neutral-icon-no-background', title: 'Neutral icon no background badge component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./neutral-icon-only/neutral-icon-only.docs').then(m => m.NeutralIconOnlyBadgeComponent), path: 'neutral-icon-only', title: 'Neutral icon only badge component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./neutral-label-only/neutral-label-only.docs').then(m => m.NeutralLabelOnlyBadgeComponent), path: 'neutral-label-only', title: 'Neutral label only badge component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./neutral-no-background/neutral-no-background.docs').then(m => m.NeutralNoBackgroundBadgeComponent), path: 'neutral-no-background', title: 'Neutral no background badge component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./neutral-number/neutral-number.docs').then(m => m.NeutralNumberBadgeComponent), path: 'neutral-number', title: 'Neutral number badge component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./neutral-number-no-background/neutral-number-no-background.docs').then(m => m.NeutralNumberNoBackgroundBadgeComponent), path: 'neutral-number-no-background', title: 'Neutral number no background badge component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./neutral-with-ellipse/neutral-with-ellipse.docs').then(m => m.NeutralWithEllipseBadgeComponent), path: 'neutral-with-ellipse', title: 'Neutral with ellipse badge component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./neutral-with-icon/neutral-with-icon.docs').then(m => m.NeutralWithIconBadgeComponent), path: 'neutral-with-icon', title: 'Neutral with icon badge component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./number/number.docs').then(m => m.NumberBadgeComponent), path: 'number', title: 'Number badge component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./number-no-background/number-no-background.docs').then(m => m.NumberNoBackgroundBadgeComponent), path: 'number-no-background', title: 'Number no background badge component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./stable-icon-no-background/stable-icon-no-background.docs').then(m => m.StableIconNoBackgroundBadgeComponent), path: 'stable-icon-no-background', title: 'Stable icon no background badge component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./stable-icon-only/stable-icon-only.docs').then(m => m.StableIconOnlyBadgeComponent), path: 'stable-icon-only', title: 'Stable icon only badge component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./stable-label-only/stable-label-only.docs').then(m => m.StableLabelOnlyBadgeComponent), path: 'stable-label-only', title: 'Stable label only badge component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./stable-no-background/stable-no-background.docs').then(m => m.StableNoBackgroundBadgeComponent), path: 'stable-no-background', title: 'Stable no background badge component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./stable-number/stable-number.docs').then(m => m.StableNumberBadgeComponent), path: 'stable-number', title: 'Stable number badge component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./stable-number-no-background/stable-number-no-background.docs').then(m => m.StableNumberNoBackgroundBadgeComponent), path: 'stable-number-no-background', title: 'Stable number no background badge component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./stable-with-ellipse/stable-with-ellipse.docs').then(m => m.StableWithEllipseBadgeComponent), path: 'stable-with-ellipse', title: 'Stable with ellipse badge component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./stable-with-icon/stable-with-icon.docs').then(m => m.StableWithIconBadgeComponent), path: 'stable-with-icon', title: 'Stable with icon badge component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./subtle-icon-no-background/subtle-icon-no-background.docs').then(m => m.SubtleIconNoBackgroundBadgeComponent), path: 'subtle-icon-no-background', title: 'Subtle icon no background badge component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./subtle-icon-only/subtle-icon-only.docs').then(m => m.SubtleIconOnlyBadgeComponent), path: 'subtle-icon-only', title: 'Subtle icon only badge component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./subtle-label-only/subtle-label-only.docs').then(m => m.SubtleLabelOnlyBadgeComponent), path: 'subtle-label-only', title: 'Subtle label only badge component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./subtle-no-background/subtle-no-background.docs').then(m => m.SubtleNoBackgroundBadgeComponent), path: 'subtle-no-background', title: 'Subtle no background badge component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./subtle-number/subtle-number.docs').then(m => m.SubtleNumberBadgeComponent), path: 'subtle-number', title: 'Subtle number badge component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./subtle-number-no-background/subtle-number-no-background.docs').then(m => m.SubtleNumberNoBackgroundBadgeComponent), path: 'subtle-number-no-background', title: 'Subtle number no background badge component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./subtle-with-ellipse/subtle-with-ellipse.docs').then(m => m.SubtleWithEllipseBadgeComponent), path: 'subtle-with-ellipse', title: 'Subtle with ellipse badge component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./subtle-with-icon/subtle-with-icon.docs').then(m => m.SubtleWithIconBadgeComponent), path: 'subtle-with-icon', title: 'Subtle with icon badge component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./warning-icon-no-background/warning-icon-no-background.docs').then(m => m.WarningIconNoBackgroundBadgeComponent), path: 'warning-icon-no-background', title: 'Warning icon no background badge component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./warning-icon-only/warning-icon-only.docs').then(m => m.WarningIconOnlyBadgeComponent), path: 'warning-icon-only', title: 'Warning icon only badge component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./warning-label-only/warning-label-only.docs').then(m => m.WarningLabelOnlyBadgeComponent), path: 'warning-label-only', title: 'Warning label only badge component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./warning-no-background/warning-no-background.docs').then(m => m.WarningNoBackgroundBadgeComponent), path: 'warning-no-background', title: 'Warning no background badge component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./warning-number/warning-number.docs').then(m => m.WarningNumberBadgeComponent), path: 'warning-number', title: 'Warning number badge component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./warning-number-no-background/warning-number-no-background.docs').then(m => m.WarningNumberNoBackgroundBadgeComponent), path: 'warning-number-no-background', title: 'Warning number no background badge component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./warning-with-ellipse/warning-with-ellipse.docs').then(m => m.WarningWithEllipseBadgeComponent), path: 'warning-with-ellipse', title: 'Warning with ellipse badge component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./warning-with-icon/warning-with-icon.docs').then(m => m.WarningWithIconBadgeComponent), path: 'warning-with-icon', title: 'Warning with icon badge component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX }
];

export default badgeRoutes;