/**
 *              © 2025 Visa
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 **/
/** This file is autogenerated */
import { Routes } from '@angular/router';
import { TITLE_SEPARATOR, TITLE_SUFFIX } from 'apps/workshop/src/assets/app.constants';

export const flexRoutes: Routes = [
	{ loadComponent: () => import('./flex.docs').then(m => m.FlexComponent), path: '' },
	{ loadComponent: () => import('./align-content-around/align-content-around.docs').then(m => m.AlignContentAroundComponent), path: 'align-content-around', title: 'Align content around flex utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./align-content-center/align-content-center.docs').then(m => m.AlignContentCenterComponent), path: 'align-content-center', title: 'Align content center flex utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./align-content-end/align-content-end.docs').then(m => m.AlignContentEndComponent), path: 'align-content-end', title: 'Align content end flex utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./align-content-evenly/align-content-evenly.docs').then(m => m.AlignContentEvenlyComponent), path: 'align-content-evenly', title: 'Align content evenly flex utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./align-content-space-between/align-content-space-between.docs').then(m => m.AlignContentBetweenComponent), path: 'align-content-space-between', title: 'Align content space between flex utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./align-content-start/align-content-start.docs').then(m => m.AlignContentStartComponent), path: 'align-content-start', title: 'Align content start flex utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./align-items-baseline/align-items-baseline.docs').then(m => m.AlignItemsBaselineComponent), path: 'align-items-baseline', title: 'Align items baseline flex utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./align-items-center/align-items-center.docs').then(m => m.AlignItemsCenterComponent), path: 'align-items-center', title: 'Align items center flex utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./align-items-end/align-items-end.docs').then(m => m.AlignItemsEndComponent), path: 'align-items-end', title: 'Align items end flex utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./align-items-start/align-items-start.docs').then(m => m.AlignItemsStartComponent), path: 'align-items-start', title: 'Align items start flex utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./align-items-stretch/align-items-stretch.docs').then(m => m.AlignItemsStretchComponent), path: 'align-items-stretch', title: 'Align items stretch flex utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./align-self-auto/align-self-auto.docs').then(m => m.AlignSelfAutoComponent), path: 'align-self-auto', title: 'Align self auto flex utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./align-self-center/align-self-center.docs').then(m => m.AlignSelfCenterComponent), path: 'align-self-center', title: 'Align self center flex utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./align-self-end/align-self-end.docs').then(m => m.AlignSelfEndComponent), path: 'align-self-end', title: 'Align self end flex utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./align-self-start/align-self-start.docs').then(m => m.AlignSelfStartComponent), path: 'align-self-start', title: 'Align self start flex utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./align-self-stretch/align-self-stretch.docs').then(m => m.AlignSelfStretchComponent), path: 'align-self-stretch', title: 'Align self stretch flex utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./column/column.docs').then(m => m.ColumnComponent), path: 'column', title: 'Column flex utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./column-reverse/column-reverse.docs').then(m => m.ColumnReverseComponent), path: 'column-reverse', title: 'Column reverse flex utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./container/container.docs').then(m => m.ContainerComponent), path: 'container', title: 'Container flex utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./grow/grow.docs').then(m => m.GrowComponent), path: 'grow', title: 'Grow flex utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./grow-0/grow-0.docs').then(m => m.Grow0Component), path: 'grow-0', title: 'Grow 0 flex utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./inline-container/inline-container.docs').then(m => m.InlineContainerComponent), path: 'inline-container', title: 'Inline container flex utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./justify-content-around/justify-content-around.docs').then(m => m.JustifyContentAroundComponent), path: 'justify-content-around', title: 'Justify content around flex utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./justify-content-between/justify-content-between.docs').then(m => m.JustifyContentBetweenComponent), path: 'justify-content-between', title: 'Justify content between flex utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./justify-content-center/justify-content-center.docs').then(m => m.JustifyContentCenterComponent), path: 'justify-content-center', title: 'Justify content center flex utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./justify-content-end/justify-content-end.docs').then(m => m.JustifyContentEndComponent), path: 'justify-content-end', title: 'Justify content end flex utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./justify-content-evenly/justify-content-evenly.docs').then(m => m.JustifyContentEvenlyComponent), path: 'justify-content-evenly', title: 'Justify content evenly flex utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./justify-content-start/justify-content-start.docs').then(m => m.JustifyContentStartComponent), path: 'justify-content-start', title: 'Justify content start flex utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./no-wrap/no-wrap.docs').then(m => m.NoWrapComponent), path: 'no-wrap', title: 'No wrap flex utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./row/row.docs').then(m => m.RowComponent), path: 'row', title: 'Row flex utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./row-reverse/row-reverse.docs').then(m => m.RowReverseComponent), path: 'row-reverse', title: 'Row reverse flex utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./shrink/shrink.docs').then(m => m.ShrinkComponent), path: 'shrink', title: 'Shrink flex utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./shrink-0/shrink-0.docs').then(m => m.Shrink0Component), path: 'shrink-0', title: 'Shrink 0 flex utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./wrap/wrap.docs').then(m => m.WrapComponent), path: 'wrap', title: 'Wrap flex utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./wrap-reverse/wrap-reverse.docs').then(m => m.WrapReverseComponent), path: 'wrap-reverse', title: 'Wrap reverse flex utility | Example' + TITLE_SEPARATOR + TITLE_SUFFIX }
];

export default flexRoutes;