/**
 *              Copyright (c) 2025 Visa, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 **/
/** This file is autogenerated */
import { Routes } from '@angular/router';
import { TITLE_SEPARATOR, TITLE_SUFFIX } from 'apps/workshop/src/assets/app.constants';

export const dialogRoutes: Routes = [
	{ loadComponent: () => import('./dialog.docs').then(m => m.DialogDocsComponent), path: '' },
	{ loadComponent: () => import('./confirmation-dialog/confirmation-dialog.docs').then(m => m.NovaConfirmationDialogComponent), path: 'confirmation-dialog', title: 'Confirmation dialog dialog component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./default/default.docs').then(m => m.NovaDefaultDialogComponent), path: 'default', title: 'Default dialog component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./error/error.docs').then(m => m.NovaErrorDialogComponent), path: 'error', title: 'Error dialog component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./success/success.docs').then(m => m.NovaSuccessDialogComponent), path: 'success', title: 'Success dialog component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./touring-tips/touring-tips.docs').then(m => m.NovaTouringTipsDialogComponent), path: 'touring-tips', title: 'Touring tips dialog component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./warning/warning.docs').then(m => m.NovaWarningDialogComponent), path: 'warning', title: 'Warning dialog component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./without-close-button/without-close-button.docs').then(m => m.NovaWithoutCloseButtonDialogComponent), path: 'without-close-button', title: 'Without close button dialog component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX }
];

export default dialogRoutes;