/**
 *              © 2025 Visa
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 **/
/** This file is autogenerated */
import { Routes } from '@angular/router';
import { TITLE_SEPARATOR, TITLE_SUFFIX } from 'apps/workshop/src/assets/app.constants';

export const footerRoutes: Routes = [
	{ loadComponent: () => import('./footer.docs').then(m => m.FooterDocsComponent), path: '' },
	{ loadComponent: () => import('./default/default.docs').then(m => m.NovaFooterDefaultComponent), path: 'default', title: 'Default footer component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./extended/extended.docs').then(m => m.NovaFooterExtendedComponent), path: 'extended', title: 'Extended footer component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX }
];

export default footerRoutes;