/**
 *              Copyright (c) 2025 Visa, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 **/
/** This file is autogenerated */
import { Routes } from '@angular/router';
import { TITLE_SEPARATOR, TITLE_SUFFIX } from 'apps/workshop/src/assets/app.constants';

export const progressRoutes: Routes = [
	{ loadComponent: () => import('./progress.docs').then(m => m.ProgressDocsComponent), path: '' },
	{ loadComponent: () => import('./completed-progress-bar/completed-progress-bar.docs').then(m => m.NovaCompletedProgressBarProgressComponent), path: 'completed-progress-bar', title: 'Completed progress bar progress component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./custom-linear-progress/custom-linear-progress.docs').then(m => m.NovaCustomLinearProgressComponent), path: 'custom-linear-progress', title: 'Custom linear progress progress component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./custom-size-circular-progress/custom-size-circular-progress.docs').then(m => m.NovaCustomSizeCircularProgressComponent), path: 'custom-size-circular-progress', title: 'Custom size circular progress progress component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./custom-slow-circular-progress/custom-slow-circular-progress.docs').then(m => m.NovaCustomSlowCircularProgressComponent), path: 'custom-slow-circular-progress', title: 'Custom slow circular progress progress component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./determinate-circular-progress/determinate-circular-progress.docs').then(m => m.NovaDeterminateCircularProgressComponent), path: 'determinate-circular-progress', title: 'Determinate circular progress progress component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./determinate-circular-progress-completed/determinate-circular-progress-completed.docs').then(m => m.NovaDeterminateCircularProgressCompletedComponent), path: 'determinate-circular-progress-completed', title: 'Determinate circular progress completed progress component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./determinate-circular-progress-small/determinate-circular-progress-small.docs').then(m => m.NovaDeterminateCircularSmallProgressComponent), path: 'determinate-circular-progress-small', title: 'Determinate circular progress small progress component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./determinate-progress-bar/determinate-progress-bar.docs').then(m => m.NovaDeterminateProgressBarProgressComponent), path: 'determinate-progress-bar', title: 'Determinate progress bar progress component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./determinate-progress-bar-no-label/determinate-progress-bar-no-label.docs').then(m => m.NovaDeterminateProgressBarNoLabelProgressComponent), path: 'determinate-progress-bar-no-label', title: 'Determinate progress bar no label progress component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./error-circular-progress/error-circular-progress.docs').then(m => m.NovaErrorProgressCircularProgressComponent), path: 'error-circular-progress', title: 'Error circular progress progress component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./error-progress-bar/error-progress-bar.docs').then(m => m.NovaErrorProgressBarProgressComponent), path: 'error-progress-bar', title: 'Error progress bar progress component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./indeterminate-circular-progress/indeterminate-circular-progress.docs').then(m => m.NovaIndeterminateCircularProgressComponent), path: 'indeterminate-circular-progress', title: 'Indeterminate circular progress progress component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./indeterminate-circular-progress-small/indeterminate-circular-progress-small.docs').then(m => m.NovaIndeterminateCircularProgressSmallComponent), path: 'indeterminate-circular-progress-small', title: 'Indeterminate circular progress small progress component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./indeterminate-progress-bar/indeterminate-progress-bar.docs').then(m => m.NovaIndeterminateProgressBarProgressComponent), path: 'indeterminate-progress-bar', title: 'Indeterminate progress bar progress component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./indeterminate-progress-bar-no-label/indeterminate-progress-bar-no-label.docs').then(m => m.NovaIndeterminateProgressBarNoLabelProgressComponent), path: 'indeterminate-progress-bar-no-label', title: 'Indeterminate progress bar no label progress component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./live-circular-progress/live-circular-progress.docs').then(m => m.NovaLiveCircularProgressComponent), path: 'live-circular-progress', title: 'Live circular progress progress component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./live-progress-bar/live-progress-bar.docs').then(m => m.NovaLiveProgressBarProgressComponent), path: 'live-progress-bar', title: 'Live progress bar progress component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX }
];

export default progressRoutes;