/**
 *              © 2025 Visa
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 **/
/** This file is autogenerated */
import { Routes } from '@angular/router';
import { TITLE_SEPARATOR, TITLE_SUFFIX } from 'apps/workshop/src/assets/app.constants';

export const panelRoutes: Routes = [
	{ loadComponent: () => import('./panel.docs').then(m => m.PanelDocsComponent), path: '' },
	{ loadComponent: () => import('./modal-default/modal-default.docs').then(m => m.ModalDefaultPanelComponent), path: 'modal-default', title: 'Modal default panel component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./modal-expandable/modal-expandable.docs').then(m => m.ModalExpandablePanelComponent), path: 'modal-expandable', title: 'Modal expandable panel component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./modal-expandable-tabbed/modal-expandable-tabbed.docs').then(m => m.ModalExpandableTabbedPanelComponent), path: 'modal-expandable-tabbed', title: 'Modal expandable tabbed panel component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./modal-expandable-with-secondary-button/modal-expandable-with-secondary-button.docs').then(m => m.ModalExpandableSecondaryButtonPanelComponent), path: 'modal-expandable-with-secondary-button', title: 'Modal expandable with secondary button panel component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./modal-expandable-with-skrim/modal-expandable-with-skrim.docs').then(m => m.ModalExpandableSkrimPanelComponent), path: 'modal-expandable-with-skrim', title: 'Modal expandable with skrim panel component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./responsive-default/responsive-default.docs').then(m => m.DefaultResponsivePanelComponent), path: 'responsive-default', title: 'Responsive default panel component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./responsive-expanded/responsive-expanded.docs').then(m => m.ResponsiveExpandedPanelComponent), path: 'responsive-expanded', title: 'Responsive expanded panel component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./responsive-expanded-tabbed/responsive-expanded-tabbed.docs').then(m => m.ResponsiveExpandedTabbedPanelComponent), path: 'responsive-expanded-tabbed', title: 'Responsive expanded tabbed panel component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./responsive-expanded-with-custom-placement/responsive-expanded-with-custom-placement.docs').then(m => m.ResposniveExpandedWithCustomPlacementPanelComponent), path: 'responsive-expanded-with-custom-placement', title: 'Responsive expanded with custom placement panel component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX }
];

export default panelRoutes;