/**
 *              © 2025 Visa
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 **/
/** This file is autogenerated */
import { Routes } from '@angular/router';
import { TITLE_SEPARATOR, TITLE_SUFFIX } from 'apps/workshop/src/assets/app.constants';

export const checkboxRoutes: Routes = [
	{ loadComponent: () => import('./checkbox.docs').then(m => m.CheckboxDocsComponent), path: '' },
	{ loadComponent: () => import('./checked/checked.docs').then(m => m.CheckedCheckboxComponent), path: 'checked', title: 'Checked checkbox component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./disabled/disabled.docs').then(m => m.DisabledCheckboxComponent), path: 'disabled', title: 'Disabled checkbox component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./disabled-checked/disabled-checked.docs').then(m => m.DisabledCheckedCheckboxComponent), path: 'disabled-checked', title: 'Disabled checked checkbox component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./disabled-panel/disabled-panel.docs').then(m => m.DisabledPanelCheckboxComponent), path: 'disabled-panel', title: 'Disabled panel checkbox component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./error/error.docs').then(m => m.ErrorCheckboxComponent), path: 'error', title: 'Error checkbox component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./group/group.docs').then(m => m.GroupCheckboxComponent), path: 'group', title: 'Group checkbox component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./group-with-error/group-with-error.docs').then(m => m.GroupWithErrorCheckboxComponent), path: 'group-with-error', title: 'Group with error checkbox component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./horizontal-group/horizontal-group.docs').then(m => m.HorizontalGroupCheckboxComponent), path: 'horizontal-group', title: 'Horizontal group checkbox component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./indeterminate-group/indeterminate-group.docs').then(m => m.IndeterminateGroupCheckboxComponent), path: 'indeterminate-group', title: 'Indeterminate group checkbox component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./indeterminate-group-with-error/indeterminate-group-with-error.docs').then(m => m.IndeterminateGroupWithErrorCheckboxComponent), path: 'indeterminate-group-with-error', title: 'Indeterminate group with error checkbox component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./indeterminate-with-error/indeterminate-with-error.docs').then(m => m.IndeterminateWithErrorCheckboxComponent), path: 'indeterminate-with-error', title: 'Indeterminate with error checkbox component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./model-driven/model-driven.docs').then(m => m.ModelDrivenCheckboxComponent), path: 'model-driven', title: 'Model driven checkbox component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./model-driven-fb/model-driven-fb.docs').then(m => m.ModelDrivenFbCheckboxComponent), path: 'model-driven-fb', title: 'Model driven fb checkbox component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./model-driven-form/model-driven-form.docs').then(m => m.ModelDrivenFormCheckboxComponent), path: 'model-driven-form', title: 'Model driven form checkbox component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./panel/panel.docs').then(m => m.PanelCheckboxComponent), path: 'panel', title: 'Panel checkbox component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./panel-group/panel-group.docs').then(m => m.PanelGroupCheckboxComponent), path: 'panel-group', title: 'Panel group checkbox component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./panel-group-with-error/panel-group-with-error.docs').then(m => m.PanelGroupWithErrorCheckboxComponent), path: 'panel-group-with-error', title: 'Panel group with error checkbox component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./panel-without-description/panel-without-description.docs').then(m => m.PanelWithoutDescriptionCheckboxComponent), path: 'panel-without-description', title: 'Panel without description checkbox component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./template-driven/template-driven.docs').then(m => m.TemplateDrivenCheckboxComponent), path: 'template-driven', title: 'Template driven checkbox component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./template-driven-form/template-driven-form.docs').then(m => m.TemplateDrivenFormCheckboxComponent), path: 'template-driven-form', title: 'Template driven form checkbox component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./with-description/with-description.docs').then(m => m.WithDescriptionCheckboxComponent), path: 'with-description', title: 'With description checkbox component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./with-label/with-label.docs').then(m => m.WithLabelCheckboxComponent), path: 'with-label', title: 'With label checkbox component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./without-visible-label/without-visible-label.docs').then(m => m.WithoutVisibleLabelCheckboxComponent), path: 'without-visible-label', title: 'Without visible label checkbox component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX }
];

export default checkboxRoutes;