/**
 *              Copyright (c) 2025 Visa, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 **/
/** This file is autogenerated */
import { Routes } from '@angular/router';
import { TITLE_SEPARATOR, TITLE_SUFFIX } from 'apps/workshop/src/assets/app.constants';

export const breadcrumbsRoutes: Routes = [
	{ loadComponent: () => import('./breadcrumbs.docs').then(m => m.BreadcrumbsDocsComponent), path: '' },
	{ loadComponent: () => import('./custom-items/custom-items.docs').then(m => m.CustomItemsBreadcrumbsComponent), path: 'custom-items', title: 'Custom items breadcrumbs component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./custom-separator/custom-separator.docs').then(m => m.CustomSeparatorBreadcrumbsComponent), path: 'custom-separator', title: 'Custom separator breadcrumbs component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./default/default.docs').then(m => m.DefaultBreadcrumbsComponent), path: 'default', title: 'Default breadcrumbs component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./inline-separator/inline-separator.docs').then(m => m.InlineSeparatorBreadcrumbsComponent), path: 'inline-separator', title: 'Inline separator breadcrumbs component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./service-based-active-crumb/service-based-active-crumb.docs').then(m => m.ServiceBasedActiveCrumbBreadcrumbsComponent), path: 'service-based-active-crumb', title: 'Service based active crumb breadcrumbs component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./svg-separator/svg-separator.docs').then(m => m.SvgSeparatorBreadcrumbsComponent), path: 'svg-separator', title: 'Svg separator breadcrumbs component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./with-observable/with-observable.docs').then(m => m.WithObservableBreadcrumbsComponent), path: 'with-observable', title: 'With observable breadcrumbs component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX }
];

export default breadcrumbsRoutes;