/**
 *              © 2025 Visa
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 **/
/** This file is autogenerated */
import { Routes } from '@angular/router';
import { TITLE_SEPARATOR, TITLE_SUFFIX } from 'apps/workshop/src/assets/app.constants';

export const horizontalNavigationRoutes: Routes = [
	{ loadComponent: () => import('./horizontal-navigation.docs').then(m => m.HorizontalNavigationDocsComponent), path: '' },
	{ loadComponent: () => import('./alternate/alternate.docs').then(m => m.AlternateHorizontalNavComponent), path: 'alternate', title: 'Alternate horizontal navigation component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./alternate-with-active-element/alternate-with-active-element.docs').then(m => m.AlternateWithActiveElementHorizontalNavComponent), path: 'alternate-with-active-element', title: 'Alternate with active element horizontal navigation component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./alternate-with-icons/alternate-with-icons.docs').then(m => m.AlternateWithIconsHorizontalNavComponent), path: 'alternate-with-icons', title: 'Alternate with icons horizontal navigation component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./default/default.docs').then(m => m.DefaultHorizontalNavComponent), path: 'default', title: 'Default horizontal navigation component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./persistent-search/persistent-search.docs').then(m => m.PersistentSearcgHorizontalNavComponent), path: 'persistent-search', title: 'Persistent search horizontal navigation component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./stacked/stacked.docs').then(m => m.StackedHorizontalNavComponent), path: 'stacked', title: 'Stacked horizontal navigation component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./stacked-with-persistent-search/stacked-with-persistent-search.docs').then(m => m.StackedWithPersistentSearchHorizontalNavComponent), path: 'stacked-with-persistent-search', title: 'Stacked with persistent search horizontal navigation component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./with-active-element/with-active-element.docs').then(m => m.WithActiveElementHorizontalNavComponent), path: 'with-active-element', title: 'With active element horizontal navigation component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./with-icons/with-icons.docs').then(m => m.WithIconsHorizontalNavComponent), path: 'with-icons', title: 'With icons horizontal navigation component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX }
];

export default horizontalNavigationRoutes;