/**
 *              Copyright (c) 2025 Visa, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 **/
/** This file is autogenerated */
import { Routes } from '@angular/router';
import { TITLE_SEPARATOR, TITLE_SUFFIX } from 'apps/workshop/src/assets/app.constants';

export const tableRoutes: Routes = [
	{ loadComponent: () => import('./table.docs').then(m => m.TableDocsComponent), path: '' },
	{ loadComponent: () => import('./compact-padding-banded-rows/compact-padding-banded-rows.docs').then(m => m.CompactPaddingBandedRowsTableComponent), path: 'compact-padding-banded-rows', title: 'Compact padding banded rows table component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./fixed-first-column/fixed-first-column.docs').then(m => m.FixedFirstColumnComponent), path: 'fixed-first-column', title: 'Fixed first column table component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./group-headers/group-headers.docs').then(m => m.GroupHeadersTableComponent), path: 'group-headers', title: 'Group headers table component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./group-headers-with-empty-cell/group-headers-with-empty-cell.docs').then(m => m.GroupHeadersWithEmptyCellTableComponent), path: 'group-headers-with-empty-cell', title: 'Group headers with empty cell table component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./key-value-table-banded/key-value-table-banded.docs').then(m => m.KeyValueTableBandedTableComponent), path: 'key-value-table-banded', title: 'Key value table banded table component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./key-value-table-lined/key-value-table-lined.docs').then(m => m.KeyValueTableLinedTableComponent), path: 'key-value-table-lined', title: 'Key value table lined table component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./large-padding-banded-rows/large-padding-banded-rows.docs').then(m => m.LargePaddingBandedRowsTableComponent), path: 'large-padding-banded-rows', title: 'Large padding banded rows table component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./lined-rows/lined-rows.docs').then(m => m.LinedRowsTableComponent), path: 'lined-rows', title: 'Lined rows table component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./medium-padding-banded-rows/medium-padding-banded-rows.docs').then(m => m.MediumPaddingBandedRowsTableComponent), path: 'medium-padding-banded-rows', title: 'Medium padding banded rows table component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./outer-border-column-and-row-dividers/outer-border-column-and-row-dividers.docs').then(m => m.OuterBorderColumnAndRowDividersTableComponent), path: 'outer-border-column-and-row-dividers', title: 'Outer border column and row dividers table component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./outer-border-subtle-headers/outer-border-subtle-headers.docs').then(m => m.OuterBorderSubtleHeadersTableComponent), path: 'outer-border-subtle-headers', title: 'Outer border subtle headers table component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./scroll/scroll.docs').then(m => m.ScrollTableComponent), path: 'scroll', title: 'Scroll table component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX }
];

export default tableRoutes;