/**
 *              © 2025 Visa
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 **/
/** This file is autogenerated */
import { Routes } from '@angular/router';
import { TITLE_SEPARATOR, TITLE_SUFFIX } from 'apps/workshop/src/assets/app.constants';

export const chipRoutes: Routes = [
	{ loadComponent: () => import('./chip.docs').then(m => m.ChipDocsComponent), path: '' },
	{ loadComponent: () => import('./compact-delete-chip-avatar/compact-delete-chip-avatar.docs').then(m => m.CompactDeleteChipAvatarChipComponent), path: 'compact-delete-chip-avatar', title: 'Compact delete chip avatar chip component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./compact-delete-chip-default/compact-delete-chip-default.docs').then(m => m.CompactDeleteChipDefaultChipComponent), path: 'compact-delete-chip-default', title: 'Compact delete chip default chip component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./compact-delete-chip-icon/compact-delete-chip-icon.docs').then(m => m.CompactDeleteChipIconChipComponent), path: 'compact-delete-chip-icon', title: 'Compact delete chip icon chip component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./custom-chip/custom-chip.docs').then(m => m.CustomChipComponent), path: 'custom-chip', title: 'Custom chip chip component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./custom-error-chip/custom-error-chip.docs').then(m => m.CustomErrorChipComponent), path: 'custom-error-chip', title: 'Custom error chip chip component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./delete-chip-avatar/delete-chip-avatar.docs').then(m => m.DeleteChipAvatarChipComponent), path: 'delete-chip-avatar', title: 'Delete chip avatar chip component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./delete-chip-default/delete-chip-default.docs').then(m => m.DeleteChipDefaultChipComponent), path: 'delete-chip-default', title: 'Delete chip default chip component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./delete-chip-disabled/delete-chip-disabled.docs').then(m => m.DeleteChipDisabledChipComponent), path: 'delete-chip-disabled', title: 'Delete chip disabled chip component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./delete-chip-icon/delete-chip-icon.docs').then(m => m.DeleteChipIconChipComponent), path: 'delete-chip-icon', title: 'Delete chip icon chip component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./disabled-selected-selection-chip/disabled-selected-selection-chip.docs').then(m => m.DisabledSelectedSelectionChipChipComponent), path: 'disabled-selected-selection-chip', title: 'Disabled selected selection chip chip component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./disabled-selection-chip/disabled-selection-chip.docs').then(m => m.DisabledSelectionChipComponent), path: 'disabled-selection-chip', title: 'Disabled selection chip chip component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./multi-line-selection-chip/multi-line-selection-chip.docs').then(m => m.MultiLineSelectionChipComponent), path: 'multi-line-selection-chip', title: 'Multi line selection chip chip component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./read-only-selection-chip/read-only-selection-chip.docs').then(m => m.ReadOnlySelectionChipComponent), path: 'read-only-selection-chip', title: 'Read only selection chip chip component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./read-only-selection-chip-checked/read-only-selection-chip-checked.docs').then(m => m.ReadOnlySelectionChipCheckedChipComponent), path: 'read-only-selection-chip-checked', title: 'Read only selection chip checked chip component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./selected-selection-chip/selected-selection-chip.docs').then(m => m.SelectedSelectionChipComponent), path: 'selected-selection-chip', title: 'Selected selection chip chip component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./selection-chip/selection-chip.docs').then(m => m.SelectionChipComponent), path: 'selection-chip', title: 'Selection chip chip component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./set-of-chips-delete-chips/set-of-chips-delete-chips.docs').then(m => m.SetOfChipsDeleteChipsChipComponent), path: 'set-of-chips-delete-chips', title: 'Set of chips delete chips chip component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./set-of-chips-delete-chips-compact/set-of-chips-delete-chips-compact.docs').then(m => m.SetOfChipsDeleteChipsCompactChipComponent), path: 'set-of-chips-delete-chips-compact', title: 'Set of chips delete chips compact chip component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./set-of-chips-selection-chip/set-of-chips-selection-chip.docs').then(m => m.SetOfChipsSelectionChipComponent), path: 'set-of-chips-selection-chip', title: 'Set of chips selection chip chip component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX },
	{ loadComponent: () => import('./standard-chip/standard-chip.docs').then(m => m.StandardChipComponent), path: 'standard-chip', title: 'Standard chip chip component | Example' + TITLE_SEPARATOR + TITLE_SUFFIX }
];

export default chipRoutes;